### ISSUE TITLE
Trouble while running , How can I solve this?

### ISSUE THREAD

**Issue by thahseeenaabdulrassak** [nariaki3551/library#124]
11:34:43 **** Incremental Build of configuration release for project SDN-Smart-Grid ****
make MODE=release all 
cd src && /usr/bin/make
make[1]: Entering directory '/c/Users/thahz/OneDrive/Desktop/Projekt/RP_Projekt/SDN-Smart-Grid/SDN-Smart-Grid/src'
Creating executable: ../out/clang-release/src/SDN-Smart-Grid.exe
lld: error: unable to find library -lopenflow6
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:104: ../out/clang-release/src/SDN-Smart-Grid.exe] Error 1
make[1]: Leaving directory '/c/Users/thahz/OneDrive/Desktop/Projekt/RP_Projekt/SDN-Smart-Grid/SDN-Smart-Grid/src'
make: *** [Makefile:2: all] Error 2
"make MODE=release all" terminated with exit code 2. Build might be incomplete.

11:34:44 Build Failed. 2 errors, 0 warnings. (took 1s.224ms)

**Comment by nariaki3551** [comment]
I don't know how to solve your question.
